### ISSUE TITLE
多卡问题

### ISSUE THREAD

**Issue by Capt-Rayn** [wzzzd/text_classifier_pytorch#12]
您好，我这边多卡训练的时候，将cuda_visible_devices设置为'0,1'，报错：
Traceback (most recent call last):
  File "main.py", line 41, in <module>
    trainer.train()
  File "/apdcephfs/private_cryanxu/program/text_classifier_pytorch-main/module/Trainer.py", line 207, in train
    loss = self.step(batch)
  File "/apdcephfs/private_cryanxu/program/text_classifier_pytorch-main/module/Trainer.py", line 249, in step
    loss.backward()
  File "/root/anaconda3/envs/text_classifier_pytorch/lib/python3.7/site-packages/torch/tensor.py", line 245, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/root/anaconda3/envs/text_classifier_pytorch/lib/python3.7/site-packages/torch/autograd/__init__.py", line 147, in backward
    allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [768, 10]], which is output 0 of TBackward, is at version 2; expected version 1 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

但是单卡训练的时候没问题，网上查了很多办法都没有解决，请教下您

**Comment by DuL1nk** [comment]
Trainer里把模型转ddp的时候加一个参数broadcast_buffers=False
